spring:
 cloud:
   gateway:
     routes:
       - id: swiggy-app
         uri: lb://SWIGGY-APP
         predicates:
           - Path=/swiggy/**
       - id: restaurant-service
         uri: lb://RESTAURANT-SERVICE
         predicates:
           - Path=/restaurant/**
       - id: identity-service
         uri: lb://IDENTITY-SERVICE
         predicates:
           - Path=/auth/**

 application:
   name: SWIGGY-GATEWAY

#IMPORTANT
 security:
   oauth2:
     resourceserver:
       jwt:
         issuer-uri: http://localhost:9080/realms/giro-users-keycloak-realm #IMPORTANT set the realm we created at keycloak

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/